/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CENTRO_H_RPCGEN
#define _CENTRO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define CENTRO_PROG 0x31111111
#define CENTRO_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ASKFORTIME 1
extern  int * askfortime_1(void *, CLIENT *);
extern  int * askfortime_1_svc(void *, struct svc_req *);
#define ASKFORSUPPLY 2
extern  int * askforsupply_1(char *, CLIENT *);
extern  int * askforsupply_1_svc(char *, struct svc_req *);
extern int centro_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ASKFORTIME 1
extern  int * askfortime_1();
extern  int * askfortime_1_svc();
#define ASKFORSUPPLY 2
extern  int * askforsupply_1();
extern  int * askforsupply_1_svc();
extern int centro_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CENTRO_H_RPCGEN */
