/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpcentrega.h"
#include "util.h"

int *
askfortime_1_svc(void *argp, struct svc_req *rqstp)
{
	static int result;

	char stringToFile[256];
    int timeT = executionTime;   

    printf("Me pidieron tiempo\n");

    if( inventory == maximumCapacity ){

		sprintf( stringToFile, "Tanque Lleno: %d minutos", executionTime );
		writeInFile(stringToFile);
    }

	result = timeT;

	return &result;
}

int *
askforsupply_1_svc(char *argp, struct svc_req *rqstp)
{
	static int result;
	char* nameBomba;
	strcpy( nameBomba, argp );

	char stringToFile[256];
    int i = 0;

    printf("Me pidieron suministro\n");

    if( inventory == maximumCapacity ){

		sprintf( stringToFile, "Tanque Lleno: %d minutos", executionTime );
		writeInFile(stringToFile);
    }
	
	printf("Cliente solicito suministro\n");
	    
	i = inventory;

	if (!check_ticket(rl, nameBomba)){
		result = 2;
		return &result;
	}
	
	if( i >= 38000 ){
	    printf("Tengo suficiente inventario, despachando...\n");
	    empty();
	    sprintf( stringToFile, "Suministro: %d min, %s, OK, %d l", executionTime, nameBomba, inventory );
	    writeInFile(stringToFile);
	    i = inventory;
		
	    if( i == 0 ){
			sprintf( stringToFile, "Tanque Vacio: %d min", executionTime );
			writeInFile(stringToFile);
	    }
	    result = 0;

	} else {
	    printf("No tengo suficiente inventario\n");
	    sprintf( stringToFile, "Suministro: %d min, %s, Sin inventario, %d l", executionTime, nameBomba,inventory );
	    writeInFile(stringToFile);
	    result = 1;
	}

	return &result;
}

/*
* argv is the name of the gas station and the function is call with "gasStation" var
*/
int *
autentificarbomba_1_svc(char *argp, struct svc_req *rqstp)
{
	static int result;
	/*
	Recorrer la lista y hacer una búsqueda lineal y ver si el elemento está en la lista, si lo está devuelvo el seed,
	si no, lo creo y lo devuelvo.
	Ver el principio de la lista y recorrerlo
	*/

	result = list_search( rl, argp );

	if( result < 0 ){
		/*No existe el elemento en la lista*/
		/*Debo crear el seed*/
		result = rand() % 100;
		
		list_add( result, argp );
	}
		//printlist( rl );


	return &result;
}

int *
confirm_1_svc(char *argp, struct svc_req *rqstp)
{
	static int result;

 	node *aux = (*rl).begin;

 	while( aux != NULL ){
 		if( strcmp( argp, (*aux).key ) == 0 ){
 			printf("confirm\n\n\n\n");
 			if (((*aux).ticketTime + 60) > executionTime){
 				printf("increment the ticket time\n\n\n\n");
 				(*aux).ticketTime = executionTime;
 			}

 			result = 1;
 			return &result;
 		}
 		aux = (*aux).next;
 	}

 	result = 0;

	return &result;
}
