/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCENTREGA_H_RPCGEN
#define _RPCENTREGA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define RPCENTREGA_PROG 0x31111111
#define RPCENTREGA_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ASKFORTIME 1
extern  int * askfortime_1(void *, CLIENT *);
extern  int * askfortime_1_svc(void *, struct svc_req *);
#define ASKFORSUPPLY 2
extern  int * askforsupply_1(char *, CLIENT *);
extern  int * askforsupply_1_svc(char *, struct svc_req *);
#define AUTENTIFICARBOMBA 3
extern  int * autentificarbomba_1(char *, CLIENT *);
extern  int * autentificarbomba_1_svc(char *, struct svc_req *);
#define CONFIRM 4
extern  int * confirm_1(char *, CLIENT *);
extern  int * confirm_1_svc(char *, struct svc_req *);
extern int rpcentrega_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ASKFORTIME 1
extern  int * askfortime_1();
extern  int * askfortime_1_svc();
#define ASKFORSUPPLY 2
extern  int * askforsupply_1();
extern  int * askforsupply_1_svc();
#define AUTENTIFICARBOMBA 3
extern  int * autentificarbomba_1();
extern  int * autentificarbomba_1_svc();
#define CONFIRM 4
extern  int * confirm_1();
extern  int * confirm_1_svc();
extern int rpcentrega_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCENTREGA_H_RPCGEN */
